name: Riikka Koskenrannan sivut
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
gems:
  - jekyll-redirect-from
safe: true
lsi: false
highlighter: pygments
url: http://riikka.koskenranta.fi
baseurl:
semester: 2015-2016

defaults:
  -
    scope:
      path: ""
    values:
      period: 3
  -
    scope:
      path: "kurssit/2013-2014"
    values:
      semester: "2013-2014"
      archived: true
  -
    scope:
      path: "kurssit/2014-2015"
    values:
      semester: "2014-2015"
      current: false
      archived: true
  -
    scope:
      path: "kurssit/2015-2016"
    values:
      semester: "2015-2016"
      current: true
      archived: false

exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gruntfile.coffee
  - bower.json
  - package.json
  - riikkak.github.io.iml
  - libpeerconnection.log
  - less
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - atlassian-ide-plugin.xml

prose:
  siteurl: 'http://riikka.koskenranta.fi'
  media: 'media'
  relativeLinks: 'http://riikka.koskenranta.fi/api/links.jsonp'
  site:
    tags: "http://riikka.koskenranta.fi/api/tags.jsonp"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "tags"
        field:
          element: "select"
          label: "Valitse sivu"
          placeholder: "Valitse"
          options:
            - name: "RUB2.2 - Etusivu"
              value: "rub2.2 etusivu"
            - name: "RUB2.2 - Läksyt"
              value: "rub2.2 läksyt"
            - name: "RUB4.5 - Etusivu"
              value: "rub4.5 etusivu"
            - name: "RUB4.5 - Läksyt"
              value: "rub4.5 läksyt"
            - name: "RUB10.4 - Etusivu"
              value: "rub10.4 etusivu"
            - name: "RUB10.4 - Läksyt"
              value: "rub10.4 läksyt"
            - name: "RUB11.3 - Etusivu"
              value: "rub11.3 etusivu"
            - name: "RUB11.3 - Läksyt"
              value: "rub11.3 läksyt"              
            - name: "Blogi"
              value: "blogi"
