name: Riikka Koskenrannan sivut
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
baseurl:

exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gruntfile.coffee
  - bower.json
  - package.json
  - riikkak.github.io.iml
  - libpeerconnection.log
  - less
  - node_modules

prose:
  siteurl: 'http://riikka.koskenranta.fi'
  rooturl: '_posts'
  media: 'media'
  relativeLinks: 'http://riikka.koskenranta.fi/api/links.jsonp'
  site:
    tags: "http://riikka.koskenranta.fi/api/tags.jsonp"
