name: Riikka Koskenrannan sivut
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
baseurl:

exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gruntfile.coffee
  - bower.json
  - package.json
  - riikkak.github.io.iml
  - libpeerconnection.log
  - less
  - node_modules

prose:
  siteurl: 'http://riikka.koskenranta.fi'
  rooturl: '_posts'
  media: 'media'
  relativeLinks: 'http://riikka.koskenranta.fi/api/links.jsonp'
  site:
    tags: "http://riikka.koskenranta.fi/api/tags.jsonp"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "tags"
        field:
          element: "select"
          label: "Valitse sivu"
          placeholder: "Valitse"
          options:
            - name: "ENA1 - Etusivu"
              value: "ena1 etusivu"
            - name: "ENA1 - Läksyt"
              value: "ena1 läksyt"
            - name: "ENA4 - Etusivu"
              value: "ena4 etusivu"
            - name: "ENA4 - Läksyt"
              value: "ena4 läksyt"
            - name: "RUB6 - Etusivu"
              value: "rub6 etusivu"
            - name: "RUB6 - Läksyt"
              value: "rub6 läksyt"
            - name: "Blogi"
              value: "blogi"
