name: Riikka Koskenrannan sivut
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]

exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gruntfile.coffee
  - bower.json
  - package.json
  - riikkak.github.io.iml
  - libpeerconnection.log
  - less
  - node_modules

prose:
  media: "media"
  siteurl: "http://riikka.koskenranta.fi"
  relativeLinks: 'http://riikka.koskenranta.fi/api/links.jsonp'
  site:
    tags: "http://riikka.koskenranta.fi/api/tags.jsonp"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "tags"
        field:
          element: "hidden"
          value: "blogi"
