name: Riikka Koskenrannan sivut
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "autolink", "tables", "with_toc_data"]
plugins:
  - jekyll-redirect-from
safe: true
lsi: false
highlighter: rouge
url: https://riikka.koskenranta.fi
baseurl:
semester: 2018-2019

defaults:
  -
    scope:
      path: ""
    values:
      period: 5
  -
    scope:
      path: "kurssit/2013-2014"
    values:
      semester: "2013-2014"
      archived: true
  -
    scope:
      path: "kurssit/2014-2015"
    values:
      semester: "2014-2015"
      current: false
      archived: true
  -
    scope:
      path: "kurssit/2015-2016"
    values:
      semester: "2015-2016"
      current: false
      archived: true
  -
    scope:
      path: "kurssit/2016-2017"
    values:
      semester: "2016-2017"
      current: false
      archived: true
  -
    scope:
      path: "kurssit/2017-2018"
    values:
      semester: "2017-2018"
      current: false
      archived: true
  -
    scope:
      path: "kurssit/2018-2019"
    values:
      semester: "2018-2019"
      current: true
      archived: false

exclude:
  - README.md
  - LICENSE.md
  - CNAME
  - Gruntfile.coffee
  - bower.json
  - package.json
  - riikkak.github.io.iml
  - libpeerconnection.log
  - less
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - atlassian-ide-plugin.xml
  - .idea

prose:
  siteurl: 'https://riikka.koskenranta.fi'
  media: 'media'
  relativeLinks: 'https://riikka.koskenranta.fi/api/links.jsonp'
  site:
    tags: "https://riikka.koskenranta.fi/api/tags.jsonp"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Otsikko"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Julkaise"
          value: "true"
      - name: "tags"
        field:
          element: "select"
          label: "Valitse sivu"
          placeholder: "Valitse"
          options:
            - name: "RUB6.4 - Etusivu"
              value: "rub6.4 etusivu"
            - name: "RUB6.4 - L채ksyt"
              value: "rub6.4 l채ksyt"
            - name: "RUB7.4 - Etusivu"
              value: "rub7.4 etusivu"
            - name: "RUB7.4 - L채ksyt"
              value: "rub7.4 l채ksyt"

